spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mrkt?useUnicode=true&characterEncoding=utf-8
    username: root
    password: toor
    driverClassName: com.mysql.jdbc.Driver
    
# Specify the DBMS
  jpa: 
    database: MYSQL
# Show or not log for each sql query
    show-sql: false
# Hibernate ddl auto (create, create-drop, update)
    hibernate: 
      ddl-auto: update
# Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# stripped before adding them to the entity manager)
    properties: 
      hibernate: 
        dialect: com.mrkt.config.MySQLDialectUTF8
# file upload
  http: 
    multipart: 
      enabled: true
      file-size-threshold: 0
#spring.http.multipart.location=
      max-file-size: 5Mb
      max-request-size: 10Mb
## redis
  redis: 
    host: localhost
    port: 6379
    password: 
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 3
      timeout: 0

endpoints: 
  sensitive: false
  cors: 
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      
security: 
  basic: 
    enabled: false

# logger
# logging.level.root=INFO
logging: 
  level: 
    com.mrkt: INFO
